# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
set_param xicom.use_bs_reader 1
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
create_project -in_memory -part xcku5p-ffvb676-1-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/ZXB/Desktop/ddr4_test/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/ZXB/Desktop/ddr4_test/project_1/project_1.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/ZXB/Desktop/ddr4_test/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/ZXB/Desktop/ddr4_test/src/ddr4_rw.v
  C:/Users/ZXB/Desktop/ddr4_test/src/rstn_time.v
  C:/Users/ZXB/Desktop/ddr4_test/src/ddr4_rw_top.v
}
read_ip -quiet C:/Users/ZXB/Desktop/ddr4_test/project_1/project_1.srcs/sources_1/ip/ddr4_0/ddr4_0.xci
set_property used_in_implementation false [get_files -all c:/Users/ZXB/Desktop/ddr4_test/project_1/project_1.srcs/sources_1/ip/ddr4_0/ip_1/par/ddr4_0_phy_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ZXB/Desktop/ddr4_test/project_1/project_1.srcs/sources_1/ip/ddr4_0/bd_0/ip/ip_0/bd_9054_microblaze_I_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ZXB/Desktop/ddr4_test/project_1/project_1.srcs/sources_1/ip/ddr4_0/bd_0/ip/ip_0/bd_9054_microblaze_I_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ZXB/Desktop/ddr4_test/project_1/project_1.srcs/sources_1/ip/ddr4_0/bd_0/ip/ip_1/bd_9054_rst_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ZXB/Desktop/ddr4_test/project_1/project_1.srcs/sources_1/ip/ddr4_0/bd_0/ip/ip_1/bd_9054_rst_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ZXB/Desktop/ddr4_test/project_1/project_1.srcs/sources_1/ip/ddr4_0/bd_0/ip/ip_2/bd_9054_ilmb_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ZXB/Desktop/ddr4_test/project_1/project_1.srcs/sources_1/ip/ddr4_0/bd_0/ip/ip_3/bd_9054_dlmb_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ZXB/Desktop/ddr4_test/project_1/project_1.srcs/sources_1/ip/ddr4_0/bd_0/ip/ip_6/bd_9054_lmb_bram_I_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ZXB/Desktop/ddr4_test/project_1/project_1.srcs/sources_1/ip/ddr4_0/bd_0/ip/ip_9/bd_9054_second_lmb_bram_I_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ZXB/Desktop/ddr4_test/project_1/project_1.srcs/sources_1/ip/ddr4_0/bd_0/ip/ip_10/bd_9054_iomodule_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ZXB/Desktop/ddr4_test/project_1/project_1.srcs/sources_1/ip/ddr4_0/bd_0/bd_9054_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ZXB/Desktop/ddr4_test/project_1/project_1.srcs/sources_1/ip/ddr4_0/ip_0/ddr4_0_microblaze_mcs_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ZXB/Desktop/ddr4_test/project_1/project_1.srcs/sources_1/ip/ddr4_0/ip_0/ddr4_0_microblaze_mcs_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ZXB/Desktop/ddr4_test/project_1/project_1.srcs/sources_1/ip/ddr4_0/ddr4_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ZXB/Desktop/ddr4_test/project_1/project_1.srcs/sources_1/ip/ddr4_0/par/ddr4_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ZXB/Desktop/ddr4_test/project_1/project_1.srcs/sources_1/ip/ddr4_0/bd_0/ip/ip_0/data/mb_bootloop_le.elf]
set_property used_in_implementation false [get_files -all c:/Users/ZXB/Desktop/ddr4_test/project_1/project_1.srcs/sources_1/ip/ddr4_0/ip_0/mb_bootloop_le.elf]
set_property used_in_implementation false [get_files -all c:/Users/ZXB/Desktop/ddr4_test/project_1/project_1.srcs/sources_1/ip/ddr4_0/sw/calibration_0/Debug/calibration_ddr.elf]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/ZXB/Desktop/ddr4_test/kup_ddr.xdc
set_property used_in_implementation false [get_files C:/Users/ZXB/Desktop/ddr4_test/kup_ddr.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top ddr4_rw_top -part xcku5p-ffvb676-1-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef ddr4_rw_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file ddr4_rw_top_utilization_synth.rpt -pb ddr4_rw_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
